CREATE TYPE "OrderStatus" AS ENUM (
  'Đang chờ',
  'Đã xác nhận',
  'Đang chuẩn bị',
  'Sẵn sàng',
  'Đã giao hàng',
  'Đã hủy'
);

CREATE TYPE "PaymentMethod" AS ENUM (
  'Thanh toán khi giao hàng',
  'Thanh toán Online'
);

CREATE TYPE "PaymentStatus" AS ENUM (
  'Đang chờ',
  'Đã thành toán',
  'Thanh toán thât bại',
  'Hoàn tiền'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "name" varchar NOT NULL,
  "avatar" varchar,
  "phone" varchar,
  "role" enum DEFAULT 'customer',
  "provider" varchar
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "slug" varchar UNIQUE NOT NULL,
  "description" text,
  "sortOrder" integer DEFAULT 0,
  "isActive" bool DEFAULT true
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "slug" varchar UNIQUE NOT NULL,
  "description" text,
  "basePrice" integer NOT NULL,
  "imageUrl" varchar NOT NULL,
  "isActive" bool DEFAULT true,
  "isFeatured" bool DEFAULT false,
  "categoryId" integer NOT NULL
);

CREATE TABLE "product_variants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "size" enum DEFAULT '15cm',
  "type" enum DEFAULT 'Mỏng',
  "modifiedPrice" integer DEFAULT 0,
  "isActive" bool DEFAULT true,
  "productId" integer NOT NULL
);

CREATE TABLE "ingredients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "imageUrl" varchar NOT NULL,
  "description" text,
  "price" integer DEFAULT 0,
  "isActive" bool DEFAULT true,
  "isRequired" bool DEFAULT false,
  "categoryId" integer NOT NULL
);

CREATE TABLE "product_ingredients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" integer NOT NULL,
  "ingredientId" integer NOT NULL,
  "isDefault" bool NOT NULL,
  "quantity" integer
);

CREATE TABLE "addresses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "street" varchar,
  "city" varchar NOT NULL,
  "district" varchar NOT NULL,
  "ward" varchar,
  "longitude" float NOT NULL,
  "latitude" float NOT NULL,
  "isDefault" bool DEFAULT false,
  "userId" integer NOT NULL
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNumber" varchar UNIQUE NOT NULL,
  "status" "OrderStatus" DEFAULT 'Đang chờ',
  "paymentStatus" "PaymentStatus",
  "paymentMethod" "PaymentMethod",
  "subTotal" integer,
  "deliveryFee" integer,
  "discount" integer,
  "total" integer,
  "notes" text,
  "userId" integer NOT NULL,
  "addressId" integer NOT NULL
);

CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" integer NOT NULL,
  "productId" integer NOT NULL,
  "quantity" integer DEFAULT 1,
  "variantId" integer
);

CREATE TABLE "order_item_ingredients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderItenId" integer NOT NULL,
  "ingredientId" integer NOT NULL,
  "quantity" integer DEFAULT 1
);

CREATE TABLE "carts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer
);

CREATE TABLE "cart_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quantity" integer DEFAULT 1,
  "cartId" integer NOT NULL,
  "productId" integer NOT NULL,
  "variantId" integer
);

CREATE TABLE "cart" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cartItenId" integer NOT NULL,
  "ingredientId" integer NOT NULL,
  "quantity" integer DEFAULT 1
);

CREATE TABLE "coupons" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "description" text,
  "type" enum NOT NULL,
  "value" integer NOT NULL,
  "minOrderAmount" integer DEFAULT 0,
  "maxUses" integer DEFAULT 1,
  "currentUses" integer DEFAULT 0,
  "validFrom" datetime NOT NULL,
  "validTo" datetime NOT NULL,
  "isActive" bool DEFAULT true
);

CREATE TABLE "user_coupons" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "isUsed" bool DEFAULT false,
  "usedAt" datetime,
  "userId" integer NOT NULL,
  "couponId" integer NOT NULL
);

CREATE TABLE "reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rating" integer NOT NULL,
  "comment" text,
  "userId" integer NOT NULL,
  "productId" integer NOT NULL,
  "orderId" integer NOT NULL
);

COMMENT ON COLUMN "users"."role" IS 'admin, customer';

COMMENT ON COLUMN "product_variants"."size" IS '15cm,20cm,30cm';

COMMENT ON COLUMN "product_variants"."type" IS 'Mỏng, Bình thường, Dày';

COMMENT ON COLUMN "coupons"."type" IS 'fixed, percentage';

COMMENT ON COLUMN "reviews"."rating" IS '1-5';

ALTER TABLE "products" ADD FOREIGN KEY ("categoryId") REFERENCES "categories" ("id");

ALTER TABLE "product_variants" ADD FOREIGN KEY ("productId") REFERENCES "products" ("id");

ALTER TABLE "ingredients" ADD FOREIGN KEY ("categoryId") REFERENCES "categories" ("id");

ALTER TABLE "product_ingredients" ADD FOREIGN KEY ("productId") REFERENCES "products" ("id");

ALTER TABLE "product_ingredients" ADD FOREIGN KEY ("ingredientId") REFERENCES "ingredients" ("id");

ALTER TABLE "addresses" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("addressId") REFERENCES "addresses" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("orderId") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("productId") REFERENCES "products" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("variantId") REFERENCES "product_variants" ("id");

ALTER TABLE "order_item_ingredients" ADD FOREIGN KEY ("orderItenId") REFERENCES "order_items" ("id");

ALTER TABLE "order_item_ingredients" ADD FOREIGN KEY ("ingredientId") REFERENCES "ingredients" ("id");

ALTER TABLE "carts" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cartId") REFERENCES "carts" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("productId") REFERENCES "products" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("variantId") REFERENCES "product_variants" ("id");

ALTER TABLE "cart" ADD FOREIGN KEY ("cartItenId") REFERENCES "cart_items" ("id");

ALTER TABLE "cart" ADD FOREIGN KEY ("ingredientId") REFERENCES "ingredients" ("id");

ALTER TABLE "user_coupons" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "user_coupons" ADD FOREIGN KEY ("couponId") REFERENCES "coupons" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("productId") REFERENCES "products" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("orderId") REFERENCES "orders" ("id");
